spring:
  application:
    name: trello-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#  flyway:
#    enabled: true
#    url: ${LOCAL_DB_URL}
#    user: ${LOCAL_DB_USERNAME}
#    password: ${LOCAL_DB_PASSWORD}
#    baseline-on-migrate: true
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}
    stack:
      auto: false
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
